#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
    deb-systemd-invoke enable eLinkDisplayStatus.service >/dev/null
	deb-systemd-invoke start eLinkDisplayStatus.service >/dev/null
fi