#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop eLinkDisplayStatus.service >/dev/null
	deb-systemd-invoke disable eLinkDisplayStatus.service >/dev/null
fi